# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)(
            ^vendor/|
            ^.*/__snapshots__/.*$
          )
      - id: end-of-file-fixer
        exclude: |
          (?x)(
            ^vendor/|
            ^.*/__snapshots__/.*$
          )
      # All non-bat files should end with LF
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: |
          (?x)(
           ^vendor/|
            \.bat$|
            ^.*/__snapshots__/.*$
          )
      # Bat files should be CRLF ending
      - id: mixed-line-ending
        args: ["--fix=crlf"]
        files: \.bat$
        exclude: |
          (?x)(
           ^vendor/|
            ^.*/__snapshots__/.*$
          )
  - repo: https://github.com/lietu/go-pre-commit
    rev: 8600d4e364570c909592d11ae28ef2a45c2970ad
    hooks:
      - id: gofumports
        exclude: ^vendor/
      - id: gofumpt
        exclude: ^vendor/
      - id: golangci-lint
        exclude: ^vendor/
      - id: go-mod-tidy
        exclude: ^vendor/
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
      - id: prettier
        exclude: ^vendor/
